### ISSUE TITLE
Failed to open extension

### ISSUE THREAD

**Issue by beibeix** [lorifranke/SlicerTMS#18]
![image](https://github.com/user-attachments/assets/1cda5c43-ff7a-4937-b7d4-88a90a4e8e06)

According the procedure，select extension open the folder with SlicerTMS.py，but it fails.

**Comment by beibeix** [comment]
Traceback (most recent call last):
  File "C:/ProgramData/slicer.org/Slicer 5.6.1/bin/../lib/Slicer-5.6/qt-scripted-modules/ExtensionWizard.py", line 284, in selectExtension
    xd = SlicerWizard.ExtensionDescription(sourcedir=path)
  File "C:\ProgramData\slicer.org\Slicer 5.6.1\bin\Python\SlicerWizard\ExtensionDescription.py", line 141, in __init__
    p = ExtensionProject(sourcedir, filename=cmakefile)
  File "C:\ProgramData\slicer.org\Slicer 5.6.1\bin\Python\SlicerWizard\ExtensionProject.py", line 56, in __init__
    raise OSError("%s not found" % filename)
OSError: CMakeLists.txt not found

**Comment by lorifranke** [comment]
@beibeix
Yes, alternatively, you can install SlicerTMS if you open up the Settings and then under Modules tab. You can add the path to the application by clicking the two arrows on the right of the window and selecting 'Add'. Then you will need to restart Slicer afterwards. Check out the image. 
<img width="958" alt="img2" src="https://github.com/user-attachments/assets/36d410cc-9e75-4511-bec6-d9f6322ba2e8">
